// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace BillingWebJob
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;
    using Models;

    /// <summary>
    /// Extension methods for EaBilling.
    /// </summary>
    public static partial class EaBillingExtensions
    {
            /// <summary>
            /// Api which returns EA usage records for all months and years since the
            /// account has been active.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            public static IList<BillingDetailLineItem> GetAllData(this IEaBilling operations)
            {
                return Task.Factory.StartNew(s => ((IEaBilling)s).GetAllDataAsync(), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Api which returns EA usage records for all months and years since the
            /// account has been active.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IList<BillingDetailLineItem>> GetAllDataAsync(this IEaBilling operations, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetAllDataWithHttpMessagesAsync(null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Api which returns EA usage records for the current month.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            public static IList<BillingDetailLineItem> GetCurrentMonthData(this IEaBilling operations)
            {
                return Task.Factory.StartNew(s => ((IEaBilling)s).GetCurrentMonthDataAsync(), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Api which returns EA usage records for the current month.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IList<BillingDetailLineItem>> GetCurrentMonthDataAsync(this IEaBilling operations, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetCurrentMonthDataWithHttpMessagesAsync(null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Api which returns CSP summarized invoice line items for the given month
            /// input.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='monthYear'>
            /// Provide month and year in "mm-yyyy" format. Example: "02-2016".
            /// </param>
            public static IList<BillingDetailLineItem> GetSingleMonthData(this IEaBilling operations, string monthYear)
            {
                return Task.Factory.StartNew(s => ((IEaBilling)s).GetSingleMonthDataAsync(monthYear), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Api which returns CSP summarized invoice line items for the given month
            /// input.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='monthYear'>
            /// Provide month and year in "mm-yyyy" format. Example: "02-2016".
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IList<BillingDetailLineItem>> GetSingleMonthDataAsync(this IEaBilling operations, string monthYear, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetSingleMonthDataWithHttpMessagesAsync(monthYear, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Api which returns CSP summarized invoice line items for the given month
            /// range input.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='startMonthYear'>
            /// Provide range start month and year in "mm-yyyy" format. Example: "02-2016".
            /// </param>
            /// <param name='endMonthYear'>
            /// Provide range end month and year in "mm-yyyy" format. Example: "02-2016".
            /// </param>
            public static IList<BillingDetailLineItem> GetDataForMonthRange(this IEaBilling operations, string startMonthYear, string endMonthYear)
            {
                return Task.Factory.StartNew(s => ((IEaBilling)s).GetDataForMonthRangeAsync(startMonthYear, endMonthYear), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Api which returns CSP summarized invoice line items for the given month
            /// range input.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='startMonthYear'>
            /// Provide range start month and year in "mm-yyyy" format. Example: "02-2016".
            /// </param>
            /// <param name='endMonthYear'>
            /// Provide range end month and year in "mm-yyyy" format. Example: "02-2016".
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IList<BillingDetailLineItem>> GetDataForMonthRangeAsync(this IEaBilling operations, string startMonthYear, string endMonthYear, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetDataForMonthRangeWithHttpMessagesAsync(startMonthYear, endMonthYear, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
