// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace BillingWebJob
{
    using System;
    using System.Collections.Generic;
    using System.Net.Http;
    using System.Threading;
    using System.Threading.Tasks;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Models;

    /// <summary>
    /// </summary>
    public partial interface IBillingDataApi : IDisposable
    {
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        Uri BaseUri { get; set; }

        /// <summary>
        /// Gets or sets json serialization settings.
        /// </summary>
        JsonSerializerSettings SerializationSettings { get; }

        /// <summary>
        /// Gets or sets json deserialization settings.
        /// </summary>
        JsonSerializerSettings DeserializationSettings { get; }

        /// <summary>
        /// Subscription credentials which uniquely identify client
        /// subscription.
        /// </summary>
        ServiceClientCredentials Credentials { get; }


        /// <summary>
        /// Gets the ICspBilling.
        /// </summary>
        ICspBilling CspBilling { get; }

        /// <summary>
        /// Gets the ICspSummary.
        /// </summary>
        ICspSummary CspSummary { get; }

        /// <summary>
        /// Gets the ICspUsage.
        /// </summary>
        ICspUsage CspUsage { get; }

        /// <summary>
        /// Gets the ICspUtilization.
        /// </summary>
        ICspUtilization CspUtilization { get; }

        /// <summary>
        /// Gets the IEaBilling.
        /// </summary>
        IEaBilling EaBilling { get; }

        /// <summary>
        /// Gets the IUserBilling.
        /// </summary>
        IUserBilling UserBilling { get; }

    }
}
