// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace BillingWebJob
{
    using System;
    using System.Collections.Generic;
    using System.Net.Http;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;
    using Models;

    /// <summary>
    /// EaBilling operations.
    /// </summary>
    public partial interface IEaBilling
    {
        /// <summary>
        /// Api which returns EA usage records for all months and years since
        /// the account has been active.
        /// </summary>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<IList<BillingDetailLineItem>>> GetAllDataWithHttpMessagesAsync(Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// Api which returns EA usage records for the current month.
        /// </summary>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<IList<BillingDetailLineItem>>> GetCurrentMonthDataWithHttpMessagesAsync(Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// Api which returns CSP summarized invoice line items for the given
        /// month input.
        /// </summary>
        /// <param name='monthYear'>
        /// Provide month and year in "mm-yyyy" format. Example: "02-2016".
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<IList<BillingDetailLineItem>>> GetSingleMonthDataWithHttpMessagesAsync(string monthYear, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// Api which returns CSP summarized invoice line items for the given
        /// month range input.
        /// </summary>
        /// <param name='startMonthYear'>
        /// Provide range start month and year in "mm-yyyy" format. Example:
        /// "02-2016".
        /// </param>
        /// <param name='endMonthYear'>
        /// Provide range end month and year in "mm-yyyy" format. Example:
        /// "02-2016".
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<IList<BillingDetailLineItem>>> GetDataForMonthRangeWithHttpMessagesAsync(string startMonthYear, string endMonthYear, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
    }
}
