// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace BillingWebJob
{
    using System;
    using System.Collections.Generic;
    using System.Net.Http;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;
    using Models;

    /// <summary>
    /// UserBilling operations.
    /// </summary>
    public partial interface IUserBilling
    {
        /// <summary>
        /// Api which returns usage records for an azure subscription for the
        /// current month.
        /// </summary>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<IList<UsageInfoModel>>> GetCurrentMonthDataWithHttpMessagesAsync(Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// Api which returns usage records for an azure subscription for the
        /// given month.
        /// </summary>
        /// <param name='monthYear'>
        /// Provide month and year in "mm-yyyy" format. Example: "02-2016".
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<IList<UsageInfoModel>>> GetSingleMonthDataWithHttpMessagesAsync(string monthYear, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// Api which returns usage records for an azure subscription for the
        /// given month range.
        /// </summary>
        /// <param name='startMonthYear'>
        /// Provide month and year in "yyyymm" format. Example: "022015".
        /// </param>
        /// <param name='endMonthYear'>
        /// Provide month and year in "yyyymm" format. Example: "122016".
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<IList<UsageInfoModel>>> GetDataForMonthRangeWithHttpMessagesAsync(string startMonthYear, string endMonthYear, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
    }
}
