// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System.Collections.Generic;
using Newtonsoft.Json.Linq;

namespace BillingWebJob.Models
{
    public static partial class BillingDetailLineItemCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<BillingDetailLineItem> DeserializeJson(JToken inputObject)
        {
            IList<BillingDetailLineItem> deserializedObject = new List<BillingDetailLineItem>();
            foreach (JToken iListValue in ((JArray) inputObject))
            {
                BillingDetailLineItem billingDetailLineItem = new BillingDetailLineItem();
                billingDetailLineItem.DeserializeJson(iListValue);
                deserializedObject.Add(billingDetailLineItem);
            }
            return deserializedObject;
        }
    }
}