// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using Newtonsoft.Json.Linq;

namespace BillingWebJob.Models
{
    public partial class BillingDetailLineItem
    {
        private string _accountName;

        /// <summary>
        /// Optional.
        /// </summary>
        public string AccountName
        {
            get { return this._accountName; }
            set { this._accountName = value; }
        }

        private string _accountOwnerId;

        /// <summary>
        /// Optional.
        /// </summary>
        public string AccountOwnerId
        {
            get { return this._accountOwnerId; }
            set { this._accountOwnerId = value; }
        }

        private string _additionalInfo;

        /// <summary>
        /// Optional.
        /// </summary>
        public string AdditionalInfo
        {
            get { return this._additionalInfo; }
            set { this._additionalInfo = value; }
        }

        private string _component;

        /// <summary>
        /// Optional.
        /// </summary>
        public string Component
        {
            get { return this._component; }
            set { this._component = value; }
        }

        private string _costCenter;

        /// <summary>
        /// Optional.
        /// </summary>
        public string CostCenter
        {
            get { return this._costCenter; }
            set { this._costCenter = value; }
        }

        private DateTimeOffset? _date;

        /// <summary>
        /// Optional.
        /// </summary>
        public DateTimeOffset? Date
        {
            get { return this._date; }
            set { this._date = value; }
        }

        private int? _day;

        /// <summary>
        /// Optional.
        /// </summary>
        public int? Day
        {
            get { return this._day; }
            set { this._day = value; }
        }

        private string _departmentName;

        /// <summary>
        /// Optional.
        /// </summary>
        public string DepartmentName
        {
            get { return this._departmentName; }
            set { this._departmentName = value; }
        }

        private string _downloadUrl;

        /// <summary>
        /// Optional.
        /// </summary>
        public string DownloadUrl
        {
            get { return this._downloadUrl; }
            set { this._downloadUrl = value; }
        }

        private string _extendedCost;

        /// <summary>
        /// Optional.
        /// </summary>
        public string ExtendedCost
        {
            get { return this._extendedCost; }
            set { this._extendedCost = value; }
        }

        private string _key;

        /// <summary>
        /// Optional.
        /// </summary>
        public string Key
        {
            get { return this._key; }
            set { this._key = value; }
        }

        private int? _month;

        /// <summary>
        /// Optional.
        /// </summary>
        public int? Month
        {
            get { return this._month; }
            set { this._month = value; }
        }

        private string _product;

        /// <summary>
        /// Optional.
        /// </summary>
        public string Product
        {
            get { return this._product; }
            set { this._product = value; }
        }

        private string _resourceGUID;

        /// <summary>
        /// Optional.
        /// </summary>
        public string ResourceGUID
        {
            get { return this._resourceGUID; }
            set { this._resourceGUID = value; }
        }

        private string _resourceKey;

        /// <summary>
        /// Optional.
        /// </summary>
        public string ResourceKey
        {
            get { return this._resourceKey; }
            set { this._resourceKey = value; }
        }

        private string _resourceQtyConsumed;

        /// <summary>
        /// Optional.
        /// </summary>
        public string ResourceQtyConsumed
        {
            get { return this._resourceQtyConsumed; }
            set { this._resourceQtyConsumed = value; }
        }

        private string _resourceRate;

        /// <summary>
        /// Optional.
        /// </summary>
        public string ResourceRate
        {
            get { return this._resourceRate; }
            set { this._resourceRate = value; }
        }

        private string _service;

        /// <summary>
        /// Optional.
        /// </summary>
        public string Service
        {
            get { return this._service; }
            set { this._service = value; }
        }

        private string _serviceAdministratorId;

        /// <summary>
        /// Optional.
        /// </summary>
        public string ServiceAdministratorId
        {
            get { return this._serviceAdministratorId; }
            set { this._serviceAdministratorId = value; }
        }

        private string _serviceInfo;

        /// <summary>
        /// Optional.
        /// </summary>
        public string ServiceInfo
        {
            get { return this._serviceInfo; }
            set { this._serviceInfo = value; }
        }

        private string _serviceInfo1;

        /// <summary>
        /// Optional.
        /// </summary>
        public string ServiceInfo1
        {
            get { return this._serviceInfo1; }
            set { this._serviceInfo1 = value; }
        }

        private string _serviceInfo2;

        /// <summary>
        /// Optional.
        /// </summary>
        public string ServiceInfo2
        {
            get { return this._serviceInfo2; }
            set { this._serviceInfo2 = value; }
        }

        private string _serviceRegion;

        /// <summary>
        /// Optional.
        /// </summary>
        public string ServiceRegion
        {
            get { return this._serviceRegion; }
            set { this._serviceRegion = value; }
        }

        private string _serviceResource;

        /// <summary>
        /// Optional.
        /// </summary>
        public string ServiceResource
        {
            get { return this._serviceResource; }
            set { this._serviceResource = value; }
        }

        private string _serviceSubRegion;

        /// <summary>
        /// Optional.
        /// </summary>
        public string ServiceSubRegion
        {
            get { return this._serviceSubRegion; }
            set { this._serviceSubRegion = value; }
        }

        private string _serviceType;

        /// <summary>
        /// Optional.
        /// </summary>
        public string ServiceType
        {
            get { return this._serviceType; }
            set { this._serviceType = value; }
        }

        private string _storeServiceIdentifier;

        /// <summary>
        /// Optional.
        /// </summary>
        public string StoreServiceIdentifier
        {
            get { return this._storeServiceIdentifier; }
            set { this._storeServiceIdentifier = value; }
        }

        private string _subscriptionGuid;

        /// <summary>
        /// Optional.
        /// </summary>
        public string SubscriptionGuid
        {
            get { return this._subscriptionGuid; }
            set { this._subscriptionGuid = value; }
        }

        private string _subscriptionId;

        /// <summary>
        /// Optional.
        /// </summary>
        public string SubscriptionId
        {
            get { return this._subscriptionId; }
            set { this._subscriptionId = value; }
        }

        private string _subscriptionName;

        /// <summary>
        /// Optional.
        /// </summary>
        public string SubscriptionName
        {
            get { return this._subscriptionName; }
            set { this._subscriptionName = value; }
        }

        private string _tags;

        /// <summary>
        /// Optional.
        /// </summary>
        public string Tags
        {
            get { return this._tags; }
            set { this._tags = value; }
        }

        private int? _year;

        /// <summary>
        /// Optional.
        /// </summary>
        public int? Year
        {
            get { return this._year; }
            set { this._year = value; }
        }

        /// <summary>
        /// Initializes a new instance of the BillingDetailLineItem class.
        /// </summary>
        public BillingDetailLineItem()
        {
        }

        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken accountNameValue = inputObject["AccountName"];
                if (accountNameValue != null && accountNameValue.Type != JTokenType.Null)
                {
                    this.AccountName = ((string) accountNameValue);
                }
                JToken accountOwnerIdValue = inputObject["AccountOwnerId"];
                if (accountOwnerIdValue != null && accountOwnerIdValue.Type != JTokenType.Null)
                {
                    this.AccountOwnerId = ((string) accountOwnerIdValue);
                }
                JToken additionalInfoValue = inputObject["AdditionalInfo"];
                if (additionalInfoValue != null && additionalInfoValue.Type != JTokenType.Null)
                {
                    this.AdditionalInfo = ((string) additionalInfoValue);
                }
                JToken componentValue = inputObject["Component"];
                if (componentValue != null && componentValue.Type != JTokenType.Null)
                {
                    this.Component = ((string) componentValue);
                }
                JToken costCenterValue = inputObject["CostCenter"];
                if (costCenterValue != null && costCenterValue.Type != JTokenType.Null)
                {
                    this.CostCenter = ((string) costCenterValue);
                }
                JToken dateValue = inputObject["Date"];
                if (dateValue != null && dateValue.Type != JTokenType.Null)
                {
                    this.Date = ((DateTimeOffset) dateValue);
                }
                JToken dayValue = inputObject["Day"];
                if (dayValue != null && dayValue.Type != JTokenType.Null)
                {
                    this.Day = ((int) dayValue);
                }
                JToken departmentNameValue = inputObject["DepartmentName"];
                if (departmentNameValue != null && departmentNameValue.Type != JTokenType.Null)
                {
                    this.DepartmentName = ((string) departmentNameValue);
                }
                JToken downloadUrlValue = inputObject["DownloadUrl"];
                if (downloadUrlValue != null && downloadUrlValue.Type != JTokenType.Null)
                {
                    this.DownloadUrl = ((string) downloadUrlValue);
                }
                JToken extendedCostValue = inputObject["ExtendedCost"];
                if (extendedCostValue != null && extendedCostValue.Type != JTokenType.Null)
                {
                    this.ExtendedCost = ((string) extendedCostValue);
                }
                JToken keyValue = inputObject["Key"];
                if (keyValue != null && keyValue.Type != JTokenType.Null)
                {
                    this.Key = ((string) keyValue);
                }
                JToken monthValue = inputObject["Month"];
                if (monthValue != null && monthValue.Type != JTokenType.Null)
                {
                    this.Month = ((int) monthValue);
                }
                JToken productValue = inputObject["Product"];
                if (productValue != null && productValue.Type != JTokenType.Null)
                {
                    this.Product = ((string) productValue);
                }
                JToken resourceGUIDValue = inputObject["ResourceGUID"];
                if (resourceGUIDValue != null && resourceGUIDValue.Type != JTokenType.Null)
                {
                    this.ResourceGUID = ((string) resourceGUIDValue);
                }
                JToken resourceKeyValue = inputObject["ResourceKey"];
                if (resourceKeyValue != null && resourceKeyValue.Type != JTokenType.Null)
                {
                    this.ResourceKey = ((string) resourceKeyValue);
                }
                JToken resourceQtyConsumedValue = inputObject["ResourceQtyConsumed"];
                if (resourceQtyConsumedValue != null && resourceQtyConsumedValue.Type != JTokenType.Null)
                {
                    this.ResourceQtyConsumed = ((string) resourceQtyConsumedValue);
                }
                JToken resourceRateValue = inputObject["ResourceRate"];
                if (resourceRateValue != null && resourceRateValue.Type != JTokenType.Null)
                {
                    this.ResourceRate = ((string) resourceRateValue);
                }
                JToken serviceValue = inputObject["Service"];
                if (serviceValue != null && serviceValue.Type != JTokenType.Null)
                {
                    this.Service = ((string) serviceValue);
                }
                JToken serviceAdministratorIdValue = inputObject["ServiceAdministratorId"];
                if (serviceAdministratorIdValue != null && serviceAdministratorIdValue.Type != JTokenType.Null)
                {
                    this.ServiceAdministratorId = ((string) serviceAdministratorIdValue);
                }
                JToken serviceInfoValue = inputObject["ServiceInfo"];
                if (serviceInfoValue != null && serviceInfoValue.Type != JTokenType.Null)
                {
                    this.ServiceInfo = ((string) serviceInfoValue);
                }
                JToken serviceInfo1Value = inputObject["ServiceInfo1"];
                if (serviceInfo1Value != null && serviceInfo1Value.Type != JTokenType.Null)
                {
                    this.ServiceInfo1 = ((string) serviceInfo1Value);
                }
                JToken serviceInfo2Value = inputObject["ServiceInfo2"];
                if (serviceInfo2Value != null && serviceInfo2Value.Type != JTokenType.Null)
                {
                    this.ServiceInfo2 = ((string) serviceInfo2Value);
                }
                JToken serviceRegionValue = inputObject["ServiceRegion"];
                if (serviceRegionValue != null && serviceRegionValue.Type != JTokenType.Null)
                {
                    this.ServiceRegion = ((string) serviceRegionValue);
                }
                JToken serviceResourceValue = inputObject["ServiceResource"];
                if (serviceResourceValue != null && serviceResourceValue.Type != JTokenType.Null)
                {
                    this.ServiceResource = ((string) serviceResourceValue);
                }
                JToken serviceSubRegionValue = inputObject["ServiceSubRegion"];
                if (serviceSubRegionValue != null && serviceSubRegionValue.Type != JTokenType.Null)
                {
                    this.ServiceSubRegion = ((string) serviceSubRegionValue);
                }
                JToken serviceTypeValue = inputObject["ServiceType"];
                if (serviceTypeValue != null && serviceTypeValue.Type != JTokenType.Null)
                {
                    this.ServiceType = ((string) serviceTypeValue);
                }
                JToken storeServiceIdentifierValue = inputObject["StoreServiceIdentifier"];
                if (storeServiceIdentifierValue != null && storeServiceIdentifierValue.Type != JTokenType.Null)
                {
                    this.StoreServiceIdentifier = ((string) storeServiceIdentifierValue);
                }
                JToken subscriptionGuidValue = inputObject["SubscriptionGuid"];
                if (subscriptionGuidValue != null && subscriptionGuidValue.Type != JTokenType.Null)
                {
                    this.SubscriptionGuid = ((string) subscriptionGuidValue);
                }
                JToken subscriptionIdValue = inputObject["SubscriptionId"];
                if (subscriptionIdValue != null && subscriptionIdValue.Type != JTokenType.Null)
                {
                    this.SubscriptionId = ((string) subscriptionIdValue);
                }
                JToken subscriptionNameValue = inputObject["SubscriptionName"];
                if (subscriptionNameValue != null && subscriptionNameValue.Type != JTokenType.Null)
                {
                    this.SubscriptionName = ((string) subscriptionNameValue);
                }
                JToken tagsValue = inputObject["Tags"];
                if (tagsValue != null && tagsValue.Type != JTokenType.Null)
                {
                    this.Tags = ((string) tagsValue);
                }
                JToken yearValue = inputObject["Year"];
                if (yearValue != null && yearValue.Type != JTokenType.Null)
                {
                    this.Year = ((int) yearValue);
                }
            }
        }
    }
}