// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using Newtonsoft.Json.Linq;

namespace BillingWebJob.Models
{
    public partial class CspAzureResourceUsageRecord
    {
        private DateTimeOffset? _billingEndDate;

        /// <summary>
        /// Optional.
        /// </summary>
        public DateTimeOffset? BillingEndDate
        {
            get { return this._billingEndDate; }
            set { this._billingEndDate = value; }
        }

        private DateTimeOffset? _billingStartDate;

        /// <summary>
        /// Optional.
        /// </summary>
        public DateTimeOffset? BillingStartDate
        {
            get { return this._billingStartDate; }
            set { this._billingStartDate = value; }
        }

        private string _category;

        /// <summary>
        /// Optional.
        /// </summary>
        public string Category
        {
            get { return this._category; }
            set { this._category = value; }
        }

        private string _customerBillingProfile;

        /// <summary>
        /// Optional.
        /// </summary>
        public string CustomerBillingProfile
        {
            get { return this._customerBillingProfile; }
            set { this._customerBillingProfile = value; }
        }

        private string _customerCommerceId;

        /// <summary>
        /// Optional.
        /// </summary>
        public string CustomerCommerceId
        {
            get { return this._customerCommerceId; }
            set { this._customerCommerceId = value; }
        }

        private string _customerDomain;

        /// <summary>
        /// Optional.
        /// </summary>
        public string CustomerDomain
        {
            get { return this._customerDomain; }
            set { this._customerDomain = value; }
        }

        private string _customerId;

        /// <summary>
        /// Optional.
        /// </summary>
        public string CustomerId
        {
            get { return this._customerId; }
            set { this._customerId = value; }
        }

        private string _customerName;

        /// <summary>
        /// Optional.
        /// </summary>
        public string CustomerName
        {
            get { return this._customerName; }
            set { this._customerName = value; }
        }

        private string _customerRelationshipToPartner;

        /// <summary>
        /// Optional.
        /// </summary>
        public string CustomerRelationshipToPartner
        {
            get { return this._customerRelationshipToPartner; }
            set { this._customerRelationshipToPartner = value; }
        }

        private string _customerTenantId;

        /// <summary>
        /// Optional.
        /// </summary>
        public string CustomerTenantId
        {
            get { return this._customerTenantId; }
            set { this._customerTenantId = value; }
        }

        private double? _quantityUsed;

        /// <summary>
        /// Optional.
        /// </summary>
        public double? QuantityUsed
        {
            get { return this._quantityUsed; }
            set { this._quantityUsed = value; }
        }

        private string _resourceId;

        /// <summary>
        /// Optional.
        /// </summary>
        public string ResourceId
        {
            get { return this._resourceId; }
            set { this._resourceId = value; }
        }

        private string _resourceName;

        /// <summary>
        /// Optional.
        /// </summary>
        public string ResourceName
        {
            get { return this._resourceName; }
            set { this._resourceName = value; }
        }

        private string _subcategory;

        /// <summary>
        /// Optional.
        /// </summary>
        public string Subcategory
        {
            get { return this._subcategory; }
            set { this._subcategory = value; }
        }

        private string _subscriptionContractType;

        /// <summary>
        /// Optional.
        /// </summary>
        public string SubscriptionContractType
        {
            get { return this._subscriptionContractType; }
            set { this._subscriptionContractType = value; }
        }

        private string _subscriptionId;

        /// <summary>
        /// Optional.
        /// </summary>
        public string SubscriptionId
        {
            get { return this._subscriptionId; }
            set { this._subscriptionId = value; }
        }

        private string _subscriptionName;

        /// <summary>
        /// Optional.
        /// </summary>
        public string SubscriptionName
        {
            get { return this._subscriptionName; }
            set { this._subscriptionName = value; }
        }

        private string _subscriptionStatus;

        /// <summary>
        /// Optional.
        /// </summary>
        public string SubscriptionStatus
        {
            get { return this._subscriptionStatus; }
            set { this._subscriptionStatus = value; }
        }

        private double? _totalCost;

        /// <summary>
        /// Optional.
        /// </summary>
        public double? TotalCost
        {
            get { return this._totalCost; }
            set { this._totalCost = value; }
        }

        private string _unit;

        /// <summary>
        /// Optional.
        /// </summary>
        public string Unit
        {
            get { return this._unit; }
            set { this._unit = value; }
        }

        /// <summary>
        /// Initializes a new instance of the CspAzureResourceUsageRecord class.
        /// </summary>
        public CspAzureResourceUsageRecord()
        {
        }

        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken billingEndDateValue = inputObject["BillingEndDate"];
                if (billingEndDateValue != null && billingEndDateValue.Type != JTokenType.Null)
                {
                    this.BillingEndDate = ((DateTimeOffset) billingEndDateValue);
                }
                JToken billingStartDateValue = inputObject["BillingStartDate"];
                if (billingStartDateValue != null && billingStartDateValue.Type != JTokenType.Null)
                {
                    this.BillingStartDate = ((DateTimeOffset) billingStartDateValue);
                }
                JToken categoryValue = inputObject["Category"];
                if (categoryValue != null && categoryValue.Type != JTokenType.Null)
                {
                    this.Category = ((string) categoryValue);
                }
                JToken customerBillingProfileValue = inputObject["CustomerBillingProfile"];
                if (customerBillingProfileValue != null && customerBillingProfileValue.Type != JTokenType.Null)
                {
                    this.CustomerBillingProfile = ((string) customerBillingProfileValue);
                }
                JToken customerCommerceIdValue = inputObject["CustomerCommerceId"];
                if (customerCommerceIdValue != null && customerCommerceIdValue.Type != JTokenType.Null)
                {
                    this.CustomerCommerceId = ((string) customerCommerceIdValue);
                }
                JToken customerDomainValue = inputObject["CustomerDomain"];
                if (customerDomainValue != null && customerDomainValue.Type != JTokenType.Null)
                {
                    this.CustomerDomain = ((string) customerDomainValue);
                }
                JToken customerIdValue = inputObject["CustomerId"];
                if (customerIdValue != null && customerIdValue.Type != JTokenType.Null)
                {
                    this.CustomerId = ((string) customerIdValue);
                }
                JToken customerNameValue = inputObject["CustomerName"];
                if (customerNameValue != null && customerNameValue.Type != JTokenType.Null)
                {
                    this.CustomerName = ((string) customerNameValue);
                }
                JToken customerRelationshipToPartnerValue = inputObject["CustomerRelationshipToPartner"];
                if (customerRelationshipToPartnerValue != null &&
                    customerRelationshipToPartnerValue.Type != JTokenType.Null)
                {
                    this.CustomerRelationshipToPartner = ((string) customerRelationshipToPartnerValue);
                }
                JToken customerTenantIdValue = inputObject["CustomerTenantId"];
                if (customerTenantIdValue != null && customerTenantIdValue.Type != JTokenType.Null)
                {
                    this.CustomerTenantId = ((string) customerTenantIdValue);
                }
                JToken quantityUsedValue = inputObject["QuantityUsed"];
                if (quantityUsedValue != null && quantityUsedValue.Type != JTokenType.Null)
                {
                    this.QuantityUsed = ((double) quantityUsedValue);
                }
                JToken resourceIdValue = inputObject["ResourceId"];
                if (resourceIdValue != null && resourceIdValue.Type != JTokenType.Null)
                {
                    this.ResourceId = ((string) resourceIdValue);
                }
                JToken resourceNameValue = inputObject["ResourceName"];
                if (resourceNameValue != null && resourceNameValue.Type != JTokenType.Null)
                {
                    this.ResourceName = ((string) resourceNameValue);
                }
                JToken subcategoryValue = inputObject["Subcategory"];
                if (subcategoryValue != null && subcategoryValue.Type != JTokenType.Null)
                {
                    this.Subcategory = ((string) subcategoryValue);
                }
                JToken subscriptionContractTypeValue = inputObject["SubscriptionContractType"];
                if (subscriptionContractTypeValue != null && subscriptionContractTypeValue.Type != JTokenType.Null)
                {
                    this.SubscriptionContractType = ((string) subscriptionContractTypeValue);
                }
                JToken subscriptionIdValue = inputObject["SubscriptionId"];
                if (subscriptionIdValue != null && subscriptionIdValue.Type != JTokenType.Null)
                {
                    this.SubscriptionId = ((string) subscriptionIdValue);
                }
                JToken subscriptionNameValue = inputObject["SubscriptionName"];
                if (subscriptionNameValue != null && subscriptionNameValue.Type != JTokenType.Null)
                {
                    this.SubscriptionName = ((string) subscriptionNameValue);
                }
                JToken subscriptionStatusValue = inputObject["SubscriptionStatus"];
                if (subscriptionStatusValue != null && subscriptionStatusValue.Type != JTokenType.Null)
                {
                    this.SubscriptionStatus = ((string) subscriptionStatusValue);
                }
                JToken totalCostValue = inputObject["TotalCost"];
                if (totalCostValue != null && totalCostValue.Type != JTokenType.Null)
                {
                    this.TotalCost = ((double) totalCostValue);
                }
                JToken unitValue = inputObject["Unit"];
                if (unitValue != null && unitValue.Type != JTokenType.Null)
                {
                    this.Unit = ((string) unitValue);
                }
            }
        }
    }
}