// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System.Collections.Generic;
using Newtonsoft.Json.Linq;

namespace BillingWebJob.Models
{
    public static partial class CspAzureResourceUsageRecordCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<CspAzureResourceUsageRecord> DeserializeJson(JToken inputObject)
        {
            IList<CspAzureResourceUsageRecord> deserializedObject = new List<CspAzureResourceUsageRecord>();
            foreach (JToken iListValue in ((JArray) inputObject))
            {
                CspAzureResourceUsageRecord cspAzureResourceUsageRecord = new CspAzureResourceUsageRecord();
                cspAzureResourceUsageRecord.DeserializeJson(iListValue);
                deserializedObject.Add(cspAzureResourceUsageRecord);
            }
            return deserializedObject;
        }
    }
}