// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using Newtonsoft.Json.Linq;

namespace BillingWebJob.Models
{
    public partial class ResourceAttributes
    {
        private string _etag;

        /// <summary>
        /// Optional.
        /// </summary>
        public string Etag
        {
            get { return this._etag; }
            set { this._etag = value; }
        }

        private string _objectType;

        /// <summary>
        /// Optional.
        /// </summary>
        public string ObjectType
        {
            get { return this._objectType; }
            set { this._objectType = value; }
        }

        /// <summary>
        /// Initializes a new instance of the ResourceAttributes class.
        /// </summary>
        public ResourceAttributes()
        {
        }

        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken etagValue = inputObject["Etag"];
                if (etagValue != null && etagValue.Type != JTokenType.Null)
                {
                    this.Etag = ((string) etagValue);
                }
                JToken objectTypeValue = inputObject["ObjectType"];
                if (objectTypeValue != null && objectTypeValue.Type != JTokenType.Null)
                {
                    this.ObjectType = ((string) objectTypeValue);
                }
            }
        }
    }
}