// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System.Collections.Generic;
using Newtonsoft.Json.Linq;

namespace BillingWebJob.Models
{
    public static partial class UsageBasedLineItemCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<UsageBasedLineItem> DeserializeJson(JToken inputObject)
        {
            IList<UsageBasedLineItem> deserializedObject = new List<UsageBasedLineItem>();
            foreach (JToken iListValue in ((JArray) inputObject))
            {
                UsageBasedLineItem usageBasedLineItem = new UsageBasedLineItem();
                usageBasedLineItem.DeserializeJson(iListValue);
                deserializedObject.Add(usageBasedLineItem);
            }
            return deserializedObject;
        }
    }
}