// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using Newtonsoft.Json.Linq;

namespace BillingWebJob.Models
{
    public partial class UsageBasedLineItem
    {
        private ResourceAttributes _attributes;

        /// <summary>
        /// Optional.
        /// </summary>
        public ResourceAttributes Attributes
        {
            get { return this._attributes; }
            set { this._attributes = value; }
        }

        private int? _billingProvider;

        /// <summary>
        /// Optional.
        /// </summary>
        public int? BillingProvider
        {
            get { return this._billingProvider; }
            set { this._billingProvider = value; }
        }

        private DateTimeOffset? _chargeEndDate;

        /// <summary>
        /// Optional.
        /// </summary>
        public DateTimeOffset? ChargeEndDate
        {
            get { return this._chargeEndDate; }
            set { this._chargeEndDate = value; }
        }

        private DateTimeOffset? _chargeStartDate;

        /// <summary>
        /// Optional.
        /// </summary>
        public DateTimeOffset? ChargeStartDate
        {
            get { return this._chargeStartDate; }
            set { this._chargeStartDate = value; }
        }

        private string _chargeType;

        /// <summary>
        /// Optional.
        /// </summary>
        public string ChargeType
        {
            get { return this._chargeType; }
            set { this._chargeType = value; }
        }

        private double? _consumedQuantity;

        /// <summary>
        /// Optional.
        /// </summary>
        public double? ConsumedQuantity
        {
            get { return this._consumedQuantity; }
            set { this._consumedQuantity = value; }
        }

        private double? _consumptionDiscount;

        /// <summary>
        /// Optional.
        /// </summary>
        public double? ConsumptionDiscount
        {
            get { return this._consumptionDiscount; }
            set { this._consumptionDiscount = value; }
        }

        private double? _consumptionPrice;

        /// <summary>
        /// Optional.
        /// </summary>
        public double? ConsumptionPrice
        {
            get { return this._consumptionPrice; }
            set { this._consumptionPrice = value; }
        }

        private string _currency;

        /// <summary>
        /// Optional.
        /// </summary>
        public string Currency
        {
            get { return this._currency; }
            set { this._currency = value; }
        }

        private string _customerCompanyName;

        /// <summary>
        /// Optional.
        /// </summary>
        public string CustomerCompanyName
        {
            get { return this._customerCompanyName; }
            set { this._customerCompanyName = value; }
        }

        private int? _detailLineItemId;

        /// <summary>
        /// Optional.
        /// </summary>
        public int? DetailLineItemId
        {
            get { return this._detailLineItemId; }
            set { this._detailLineItemId = value; }
        }

        private double? _includedQuantity;

        /// <summary>
        /// Optional.
        /// </summary>
        public double? IncludedQuantity
        {
            get { return this._includedQuantity; }
            set { this._includedQuantity = value; }
        }

        private int? _invoiceLineItemType;

        /// <summary>
        /// Optional.
        /// </summary>
        public int? InvoiceLineItemType
        {
            get { return this._invoiceLineItemType; }
            set { this._invoiceLineItemType = value; }
        }

        private string _invoiceNumber;

        /// <summary>
        /// Optional.
        /// </summary>
        public string InvoiceNumber
        {
            get { return this._invoiceNumber; }
            set { this._invoiceNumber = value; }
        }

        private double? _listPrice;

        /// <summary>
        /// Optional.
        /// </summary>
        public double? ListPrice
        {
            get { return this._listPrice; }
            set { this._listPrice = value; }
        }

        private int? _mpnId;

        /// <summary>
        /// Optional.
        /// </summary>
        public int? MpnId
        {
            get { return this._mpnId; }
            set { this._mpnId = value; }
        }

        private string _orderId;

        /// <summary>
        /// Optional.
        /// </summary>
        public string OrderId
        {
            get { return this._orderId; }
            set { this._orderId = value; }
        }

        private double? _overageQuantity;

        /// <summary>
        /// Optional.
        /// </summary>
        public double? OverageQuantity
        {
            get { return this._overageQuantity; }
            set { this._overageQuantity = value; }
        }

        private string _partnerBillableAccountId;

        /// <summary>
        /// Optional.
        /// </summary>
        public string PartnerBillableAccountId
        {
            get { return this._partnerBillableAccountId; }
            set { this._partnerBillableAccountId = value; }
        }

        private string _partnerId;

        /// <summary>
        /// Optional.
        /// </summary>
        public string PartnerId
        {
            get { return this._partnerId; }
            set { this._partnerId = value; }
        }

        private string _partnerName;

        /// <summary>
        /// Optional.
        /// </summary>
        public string PartnerName
        {
            get { return this._partnerName; }
            set { this._partnerName = value; }
        }

        private double? _postTaxEffectiveRate;

        /// <summary>
        /// Optional.
        /// </summary>
        public double? PostTaxEffectiveRate
        {
            get { return this._postTaxEffectiveRate; }
            set { this._postTaxEffectiveRate = value; }
        }

        private double? _postTaxTotal;

        /// <summary>
        /// Optional.
        /// </summary>
        public double? PostTaxTotal
        {
            get { return this._postTaxTotal; }
            set { this._postTaxTotal = value; }
        }

        private double? _pretaxCharges;

        /// <summary>
        /// Optional.
        /// </summary>
        public double? PretaxCharges
        {
            get { return this._pretaxCharges; }
            set { this._pretaxCharges = value; }
        }

        private double? _pretaxEffectiveRate;

        /// <summary>
        /// Optional.
        /// </summary>
        public double? PretaxEffectiveRate
        {
            get { return this._pretaxEffectiveRate; }
            set { this._pretaxEffectiveRate = value; }
        }

        private string _region;

        /// <summary>
        /// Optional.
        /// </summary>
        public string Region
        {
            get { return this._region; }
            set { this._region = value; }
        }

        private string _resourceGuid;

        /// <summary>
        /// Optional.
        /// </summary>
        public string ResourceGuid
        {
            get { return this._resourceGuid; }
            set { this._resourceGuid = value; }
        }

        private string _resourceName;

        /// <summary>
        /// Optional.
        /// </summary>
        public string ResourceName
        {
            get { return this._resourceName; }
            set { this._resourceName = value; }
        }

        private string _serviceName;

        /// <summary>
        /// Optional.
        /// </summary>
        public string ServiceName
        {
            get { return this._serviceName; }
            set { this._serviceName = value; }
        }

        private string _serviceType;

        /// <summary>
        /// Optional.
        /// </summary>
        public string ServiceType
        {
            get { return this._serviceType; }
            set { this._serviceType = value; }
        }

        private string _sku;

        /// <summary>
        /// Optional.
        /// </summary>
        public string Sku
        {
            get { return this._sku; }
            set { this._sku = value; }
        }

        private string _subscriptionDescription;

        /// <summary>
        /// Optional.
        /// </summary>
        public string SubscriptionDescription
        {
            get { return this._subscriptionDescription; }
            set { this._subscriptionDescription = value; }
        }

        private string _subscriptionId;

        /// <summary>
        /// Optional.
        /// </summary>
        public string SubscriptionId
        {
            get { return this._subscriptionId; }
            set { this._subscriptionId = value; }
        }

        private string _subscriptionName;

        /// <summary>
        /// Optional.
        /// </summary>
        public string SubscriptionName
        {
            get { return this._subscriptionName; }
            set { this._subscriptionName = value; }
        }

        private double? _taxAmount;

        /// <summary>
        /// Optional.
        /// </summary>
        public double? TaxAmount
        {
            get { return this._taxAmount; }
            set { this._taxAmount = value; }
        }

        private int? _tier2MpnId;

        /// <summary>
        /// Optional.
        /// </summary>
        public int? Tier2MpnId
        {
            get { return this._tier2MpnId; }
            set { this._tier2MpnId = value; }
        }

        /// <summary>
        /// Initializes a new instance of the UsageBasedLineItem class.
        /// </summary>
        public UsageBasedLineItem()
        {
        }

        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken attributesValue = inputObject["Attributes"];
                if (attributesValue != null && attributesValue.Type != JTokenType.Null)
                {
                    ResourceAttributes resourceAttributes = new ResourceAttributes();
                    resourceAttributes.DeserializeJson(attributesValue);
                    this.Attributes = resourceAttributes;
                }
                //JToken billingProviderValue = inputObject["BillingProvider"];
                //if (billingProviderValue != null && billingProviderValue.Type != JTokenType.Null)
                //{
                //    this.BillingProvider = ((int)billingProviderValue);
                //}
                JToken chargeEndDateValue = inputObject["ChargeEndDate"];
                if (chargeEndDateValue != null && chargeEndDateValue.Type != JTokenType.Null)
                {
                    this.ChargeEndDate = ((DateTimeOffset) chargeEndDateValue);
                }
                JToken chargeStartDateValue = inputObject["ChargeStartDate"];
                if (chargeStartDateValue != null && chargeStartDateValue.Type != JTokenType.Null)
                {
                    this.ChargeStartDate = ((DateTimeOffset) chargeStartDateValue);
                }
                JToken chargeTypeValue = inputObject["ChargeType"];
                if (chargeTypeValue != null && chargeTypeValue.Type != JTokenType.Null)
                {
                    this.ChargeType = ((string) chargeTypeValue);
                }
                JToken consumedQuantityValue = inputObject["ConsumedQuantity"];
                if (consumedQuantityValue != null && consumedQuantityValue.Type != JTokenType.Null)
                {
                    this.ConsumedQuantity = ((double) consumedQuantityValue);
                }
                JToken consumptionDiscountValue = inputObject["ConsumptionDiscount"];
                if (consumptionDiscountValue != null && consumptionDiscountValue.Type != JTokenType.Null)
                {
                    this.ConsumptionDiscount = ((double) consumptionDiscountValue);
                }
                JToken consumptionPriceValue = inputObject["ConsumptionPrice"];
                if (consumptionPriceValue != null && consumptionPriceValue.Type != JTokenType.Null)
                {
                    this.ConsumptionPrice = ((double) consumptionPriceValue);
                }
                JToken currencyValue = inputObject["Currency"];
                if (currencyValue != null && currencyValue.Type != JTokenType.Null)
                {
                    this.Currency = ((string) currencyValue);
                }
                JToken customerCompanyNameValue = inputObject["CustomerCompanyName"];
                if (customerCompanyNameValue != null && customerCompanyNameValue.Type != JTokenType.Null)
                {
                    this.CustomerCompanyName = ((string) customerCompanyNameValue);
                }
                JToken detailLineItemIdValue = inputObject["DetailLineItemId"];
                if (detailLineItemIdValue != null && detailLineItemIdValue.Type != JTokenType.Null)
                {
                    this.DetailLineItemId = ((int) detailLineItemIdValue);
                }
                JToken includedQuantityValue = inputObject["IncludedQuantity"];
                if (includedQuantityValue != null && includedQuantityValue.Type != JTokenType.Null)
                {
                    this.IncludedQuantity = ((double) includedQuantityValue);
                }
                JToken invoiceLineItemTypeValue = inputObject["InvoiceLineItemType"];
                //if (invoiceLineItemTypeValue != null && invoiceLineItemTypeValue.Type != JTokenType.Null)
                //{
                //    this.InvoiceLineItemType = ((int)invoiceLineItemTypeValue);
                //}
                JToken invoiceNumberValue = inputObject["InvoiceNumber"];
                if (invoiceNumberValue != null && invoiceNumberValue.Type != JTokenType.Null)
                {
                    this.InvoiceNumber = ((string) invoiceNumberValue);
                }
                JToken listPriceValue = inputObject["ListPrice"];
                if (listPriceValue != null && listPriceValue.Type != JTokenType.Null)
                {
                    this.ListPrice = ((double) listPriceValue);
                }
                JToken mpnIdValue = inputObject["MpnId"];
                if (mpnIdValue != null && mpnIdValue.Type != JTokenType.Null)
                {
                    this.MpnId = ((int) mpnIdValue);
                }
                JToken orderIdValue = inputObject["OrderId"];
                if (orderIdValue != null && orderIdValue.Type != JTokenType.Null)
                {
                    this.OrderId = ((string) orderIdValue);
                }
                JToken overageQuantityValue = inputObject["OverageQuantity"];
                if (overageQuantityValue != null && overageQuantityValue.Type != JTokenType.Null)
                {
                    this.OverageQuantity = ((double) overageQuantityValue);
                }
                JToken partnerBillableAccountIdValue = inputObject["PartnerBillableAccountId"];
                if (partnerBillableAccountIdValue != null && partnerBillableAccountIdValue.Type != JTokenType.Null)
                {
                    this.PartnerBillableAccountId = ((string) partnerBillableAccountIdValue);
                }
                JToken partnerIdValue = inputObject["PartnerId"];
                if (partnerIdValue != null && partnerIdValue.Type != JTokenType.Null)
                {
                    this.PartnerId = ((string) partnerIdValue);
                }
                JToken partnerNameValue = inputObject["PartnerName"];
                if (partnerNameValue != null && partnerNameValue.Type != JTokenType.Null)
                {
                    this.PartnerName = ((string) partnerNameValue);
                }
                JToken postTaxEffectiveRateValue = inputObject["PostTaxEffectiveRate"];
                if (postTaxEffectiveRateValue != null && postTaxEffectiveRateValue.Type != JTokenType.Null)
                {
                    this.PostTaxEffectiveRate = ((double) postTaxEffectiveRateValue);
                }
                JToken postTaxTotalValue = inputObject["PostTaxTotal"];
                if (postTaxTotalValue != null && postTaxTotalValue.Type != JTokenType.Null)
                {
                    this.PostTaxTotal = ((double) postTaxTotalValue);
                }
                JToken pretaxChargesValue = inputObject["PretaxCharges"];
                if (pretaxChargesValue != null && pretaxChargesValue.Type != JTokenType.Null)
                {
                    this.PretaxCharges = ((double) pretaxChargesValue);
                }
                JToken pretaxEffectiveRateValue = inputObject["PretaxEffectiveRate"];
                if (pretaxEffectiveRateValue != null && pretaxEffectiveRateValue.Type != JTokenType.Null)
                {
                    this.PretaxEffectiveRate = ((double) pretaxEffectiveRateValue);
                }
                JToken regionValue = inputObject["Region"];
                if (regionValue != null && regionValue.Type != JTokenType.Null)
                {
                    this.Region = ((string) regionValue);
                }
                JToken resourceGuidValue = inputObject["ResourceGuid"];
                if (resourceGuidValue != null && resourceGuidValue.Type != JTokenType.Null)
                {
                    this.ResourceGuid = ((string) resourceGuidValue);
                }
                JToken resourceNameValue = inputObject["ResourceName"];
                if (resourceNameValue != null && resourceNameValue.Type != JTokenType.Null)
                {
                    this.ResourceName = ((string) resourceNameValue);
                }
                JToken serviceNameValue = inputObject["ServiceName"];
                if (serviceNameValue != null && serviceNameValue.Type != JTokenType.Null)
                {
                    this.ServiceName = ((string) serviceNameValue);
                }
                JToken serviceTypeValue = inputObject["ServiceType"];
                if (serviceTypeValue != null && serviceTypeValue.Type != JTokenType.Null)
                {
                    this.ServiceType = ((string) serviceTypeValue);
                }
                JToken skuValue = inputObject["Sku"];
                if (skuValue != null && skuValue.Type != JTokenType.Null)
                {
                    this.Sku = ((string) skuValue);
                }
                JToken subscriptionDescriptionValue = inputObject["SubscriptionDescription"];
                if (subscriptionDescriptionValue != null && subscriptionDescriptionValue.Type != JTokenType.Null)
                {
                    this.SubscriptionDescription = ((string) subscriptionDescriptionValue);
                }
                JToken subscriptionIdValue = inputObject["SubscriptionId"];
                if (subscriptionIdValue != null && subscriptionIdValue.Type != JTokenType.Null)
                {
                    this.SubscriptionId = ((string) subscriptionIdValue);
                }
                JToken subscriptionNameValue = inputObject["SubscriptionName"];
                if (subscriptionNameValue != null && subscriptionNameValue.Type != JTokenType.Null)
                {
                    this.SubscriptionName = ((string) subscriptionNameValue);
                }
                JToken taxAmountValue = inputObject["TaxAmount"];
                if (taxAmountValue != null && taxAmountValue.Type != JTokenType.Null)
                {
                    this.TaxAmount = ((double) taxAmountValue);
                }
                JToken tier2MpnIdValue = inputObject["Tier2MpnId"];
                if (tier2MpnIdValue != null && tier2MpnIdValue.Type != JTokenType.Null)
                {
                    this.Tier2MpnId = ((int) tier2MpnIdValue);
                }
            }
        }
    }
}