// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

namespace BillingWebJob
{
    public static partial class AzureAnalyticsApiExtensions
    {
    }
}