// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using BillingWebJob.Models;

namespace BillingWebJob
{
    public static partial class CspUsageExtensions
    {
        /// <param name='operations'>
        /// Reference to the BillingWebJob.ICspUsage.
        /// </param>
        public static IList<CspAzureResourceUsageRecord> GetAllData(this ICspUsage operations)
        {
            return Task.Factory.StartNew((object s) => { return ((ICspUsage) s).GetAllDataAsync(); }
                    , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default)
                .Unwrap()
                .GetAwaiter()
                .GetResult();
        }

        /// <param name='operations'>
        /// Reference to the BillingWebJob.ICspUsage.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<IList<CspAzureResourceUsageRecord>> GetAllDataAsync(this ICspUsage operations,
            CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse
                <System.Collections.Generic.IList<BillingWebJob.Models.CspAzureResourceUsageRecord>> result =
                    await operations.GetAllDataWithOperationResponseAsync(cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
    }
}