// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using BillingWebJob.Models;

namespace BillingWebJob
{
    public static partial class EaBillingExtensions
    {
        /// <param name='operations'>
        /// Reference to the BillingWebJob.IEaBilling.
        /// </param>
        public static IList<BillingDetailLineItem> GetAllData(this IEaBilling operations)
        {
            return Task.Factory.StartNew((object s) => { return ((IEaBilling) s).GetAllDataAsync(); }
                    , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default)
                .Unwrap()
                .GetAwaiter()
                .GetResult();
        }

        /// <param name='operations'>
        /// Reference to the BillingWebJob.IEaBilling.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<IList<BillingDetailLineItem>> GetAllDataAsync(this IEaBilling operations,
            CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse
                <System.Collections.Generic.IList<BillingWebJob.Models.BillingDetailLineItem>> result =
                    await operations.GetAllDataWithOperationResponseAsync(cancellationToken).ConfigureAwait(false);
            return result.Body;
        }

        /// <param name='operations'>
        /// Reference to the BillingWebJob.IEaBilling.
        /// </param>
        public static IList<BillingDetailLineItem> GetCurrentMonthData(this IEaBilling operations)
        {
            return Task.Factory.StartNew((object s) => { return ((IEaBilling) s).GetCurrentMonthDataAsync(); }
                    , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default)
                .Unwrap()
                .GetAwaiter()
                .GetResult();
        }

        /// <param name='operations'>
        /// Reference to the BillingWebJob.IEaBilling.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<IList<BillingDetailLineItem>> GetCurrentMonthDataAsync(this IEaBilling operations,
            CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse
                <System.Collections.Generic.IList<BillingWebJob.Models.BillingDetailLineItem>> result =
                    await
                        operations.GetCurrentMonthDataWithOperationResponseAsync(cancellationToken)
                            .ConfigureAwait(false);
            return result.Body;
        }

        /// <param name='operations'>
        /// Reference to the BillingWebJob.IEaBilling.
        /// </param>
        /// <param name='startMMYYYY'>
        /// Required.
        /// </param>
        /// <param name='endMMYYYY'>
        /// Required.
        /// </param>
        public static IList<BillingDetailLineItem> GetDataForMonthRange(this IEaBilling operations, string startMMYYYY,
            string endMMYYYY)
        {
            return
                Task.Factory.StartNew(
                        (object s) => { return ((IEaBilling) s).GetDataForMonthRangeAsync(startMMYYYY, endMMYYYY); }
                        , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default)
                    .Unwrap()
                    .GetAwaiter()
                    .GetResult();
        }

        /// <param name='operations'>
        /// Reference to the BillingWebJob.IEaBilling.
        /// </param>
        /// <param name='startMMYYYY'>
        /// Required.
        /// </param>
        /// <param name='endMMYYYY'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<IList<BillingDetailLineItem>> GetDataForMonthRangeAsync(this IEaBilling operations,
            string startMMYYYY, string endMMYYYY,
            CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse
                <System.Collections.Generic.IList<BillingWebJob.Models.BillingDetailLineItem>> result =
                    await
                        operations.GetDataForMonthRangeWithOperationResponseAsync(startMMYYYY, endMMYYYY,
                            cancellationToken).ConfigureAwait(false);
            return result.Body;
        }

        /// <param name='operations'>
        /// Reference to the BillingWebJob.IEaBilling.
        /// </param>
        /// <param name='mMYYYY'>
        /// Required.
        /// </param>
        public static IList<BillingDetailLineItem> GetSingleMonthData(this IEaBilling operations, string mMYYYY)
        {
            return Task.Factory.StartNew((object s) => { return ((IEaBilling) s).GetSingleMonthDataAsync(mMYYYY); }
                    , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default)
                .Unwrap()
                .GetAwaiter()
                .GetResult();
        }

        /// <param name='operations'>
        /// Reference to the BillingWebJob.IEaBilling.
        /// </param>
        /// <param name='mMYYYY'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<IList<BillingDetailLineItem>> GetSingleMonthDataAsync(this IEaBilling operations,
            string mMYYYY, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse
                <System.Collections.Generic.IList<BillingWebJob.Models.BillingDetailLineItem>> result =
                    await
                        operations.GetSingleMonthDataWithOperationResponseAsync(mMYYYY, cancellationToken)
                            .ConfigureAwait(false);
            return result.Body;
        }
    }
}