// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using Microsoft.Rest;

namespace BillingWebJob
{
    public partial interface IAzureAnalyticsApi : IDisposable
    {
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        Uri BaseUri { get; set; }

        /// <summary>
        /// Credentials for authenticating with the service.
        /// </summary>
        ServiceClientCredentials Credentials { get; set; }

        ICspBilling CspBilling { get; }

        ICspSummary CspSummary { get; }

        ICspUsage CspUsage { get; }

        IEaBilling EaBilling { get; }

        IUserBilling UserBilling { get; }
    }
}