// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using BillingWebJob.Models;
using Microsoft.Rest;

namespace BillingWebJob
{
    public partial interface ICspUsage
    {
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<IList<CspAzureResourceUsageRecord>>> GetAllDataWithOperationResponseAsync(
            CancellationToken cancellationToken = default(System.Threading.CancellationToken));
    }
}