// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using BillingWebJob.Models;
using Microsoft.Rest;

namespace BillingWebJob
{
    public partial interface IEaBilling
    {
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<IList<BillingDetailLineItem>>> GetAllDataWithOperationResponseAsync(
            CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<IList<BillingDetailLineItem>>> GetCurrentMonthDataWithOperationResponseAsync(
            CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <param name='startMMYYYY'>
        /// Required.
        /// </param>
        /// <param name='endMMYYYY'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<IList<BillingDetailLineItem>>> GetDataForMonthRangeWithOperationResponseAsync(
            string startMMYYYY, string endMMYYYY,
            CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <param name='mMYYYY'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<IList<BillingDetailLineItem>>> GetSingleMonthDataWithOperationResponseAsync(
            string mMYYYY, CancellationToken cancellationToken = default(System.Threading.CancellationToken));
    }
}