CREATE TABLE [dbo].[CspSummaryData]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
    [ChargeEndDate] DATETIME NULL, 
    [ChargeStartDate] DATETIME NULL, 
    [ChargeType] NVARCHAR(1024) NULL, 
    [ConsumedQuantity] FLOAT NULL, 
    [ConsumptionDiscount] FLOAT NULL, 
    [ConsumptionPrice] FLOAT NULL, 
    [Currency] NVARCHAR(50) NULL, 
    [CustomerCompanyName] NVARCHAR(1024) NULL, 
    [DetailLineItemId] INT NULL, 
    [IncludedQuantity] FLOAT NULL, 
    [InvoiceNumber] NVARCHAR(50) NULL, 
    [ListPrice] FLOAT NULL, 
    [MpnId] INT NULL, 
    [OrderId] NVARCHAR(50) NULL, 
    [OverageQuantity] FLOAT NULL, 
    [PartnerBillingAccountId] NVARCHAR(50) NULL, 
    [PartnerId] NVARCHAR(50) NULL, 
    [PartnerName] NVARCHAR(256) NULL, 
    [PostTaxEffectiveRate] FLOAT NULL, 
    [PostTaxTotal] FLOAT NULL, 
    [PreTaxCharges] FLOAT NULL, 
    [PreTaxEffectiveRate] FLOAT NULL, 
    [Region] NVARCHAR(50) NULL, 
    [ResourceGuid] NVARCHAR(50) NULL, 
    [ResourceName] NVARCHAR(256) NULL, 
    [ServiceName] NVARCHAR(256) NULL, 
    [ServiceType] NVARCHAR(256) NULL, 
    [Sku] NVARCHAR(50) NULL, 
    [SubscriptionDescription] NVARCHAR(1024) NULL, 
    [SubscriptionId] NVARCHAR(50) NULL, 
    [SubscriptionName] NVARCHAR(256) NULL, 
    [TaxAmount] FLOAT NULL, 
    [Tier2MpnId] INT NULL
)
