CREATE TABLE [dbo].[EaBillingData]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
	[Key] VARCHAR(1024) NULL ,
    [AccountOwnerId] NVARCHAR(255) NULL, 
    [AccountName] NVARCHAR(255) NULL,
    [ServiceAdministratorId] NVARCHAR(255) NULL, 
    [SubscriptionId] NVARCHAR(255) NULL, 
    [SubscriptionGuid] NVARCHAR(255) NULL, 
    [SubscriptionName] NVARCHAR(255) NULL, 
    [Date] DATETIME NULL, 
    [Month] INT NULL, 
    [Day] INT NULL, 
    [Year] INT NULL, 
    [Product] NVARCHAR(255) NULL, 
    [ResourceGUID] NVARCHAR(255) NULL, 
    [Service] NVARCHAR(255) NULL, 
    [ServiceType] NVARCHAR(255) NULL, 
    [ServiceRegion] NVARCHAR(255) NULL, 
	[DownloadUrl] NVARCHAR(1024) NULL,
    [ServiceResource] NVARCHAR(255) NULL, 
    [ResourceQtyConsumed] REAL NULL, 
    [ResourceRate] REAL NULL, 
    [ExtendedCost] REAL NULL, 
    [ServiceSubRegion] NVARCHAR(255) NULL, 
    [ServiceInfo] NVARCHAR(255) NULL, 
    [Component] NVARCHAR(255) NULL, 
    [ServiceInfo1] NVARCHAR(1024) NULL, 
    [ServiceInfo2] NVARCHAR(1024) NULL, 
    [AdditionalInfo] NVARCHAR(1024) NULL, 
    [Tags] NVARCHAR(1024) NULL, 
    [StoreServiceIdentifier] NVARCHAR(1024) NULL, 
    [DepartmentName] NVARCHAR(255) NULL, 
    [CostCenter] NCHAR(255) NULL, 
    [ResourceKey] NVARCHAR(1024) NULL 
)
