// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace BillingWebJob.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class AzureInstanceData
    {
        /// <summary>
        /// Initializes a new instance of the AzureInstanceData class.
        /// </summary>
        public AzureInstanceData() { }

        /// <summary>
        /// Initializes a new instance of the AzureInstanceData class.
        /// </summary>
        public AzureInstanceData(string resourceUri = default(string), string location = default(string), string partNumber = default(string), string orderNumber = default(string), IDictionary<string, string> tags = default(IDictionary<string, string>))
        {
            ResourceUri = resourceUri;
            Location = location;
            PartNumber = partNumber;
            OrderNumber = orderNumber;
            Tags = tags;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ResourceUri")]
        public string ResourceUri { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Location")]
        public string Location { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PartNumber")]
        public string PartNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "OrderNumber")]
        public string OrderNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Tags")]
        public IDictionary<string, string> Tags { get; set; }

    }
}
