// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace BillingWebJob.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class AzureResource
    {
        /// <summary>
        /// Initializes a new instance of the AzureResource class.
        /// </summary>
        public AzureResource() { }

        /// <summary>
        /// Initializes a new instance of the AzureResource class.
        /// </summary>
        public AzureResource(string id = default(string), string name = default(string), string category = default(string), string subcategory = default(string))
        {
            Id = id;
            Name = name;
            Category = category;
            Subcategory = subcategory;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Category")]
        public string Category { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Subcategory")]
        public string Subcategory { get; set; }

    }
}
