// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace BillingWebJob.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class AzureUtilizationRecord
    {
        /// <summary>
        /// Initializes a new instance of the AzureUtilizationRecord class.
        /// </summary>
        public AzureUtilizationRecord() { }

        /// <summary>
        /// Initializes a new instance of the AzureUtilizationRecord class.
        /// </summary>
        public AzureUtilizationRecord(DateTime? usageStartTime = default(DateTime?), DateTime? usageEndTime = default(DateTime?), AzureResource resource = default(AzureResource), double? quantity = default(double?), string unit = default(string), IDictionary<string, string> infoFields = default(IDictionary<string, string>), AzureInstanceData instanceData = default(AzureInstanceData), ResourceAttributes attributes = default(ResourceAttributes))
        {
            UsageStartTime = usageStartTime;
            UsageEndTime = usageEndTime;
            Resource = resource;
            Quantity = quantity;
            Unit = unit;
            InfoFields = infoFields;
            InstanceData = instanceData;
            Attributes = attributes;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "UsageStartTime")]
        public DateTime? UsageStartTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "UsageEndTime")]
        public DateTime? UsageEndTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Resource")]
        public AzureResource Resource { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Quantity")]
        public double? Quantity { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Unit")]
        public string Unit { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "InfoFields")]
        public IDictionary<string, string> InfoFields { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "InstanceData")]
        public AzureInstanceData InstanceData { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Attributes")]
        public ResourceAttributes Attributes { get; private set; }

    }
}
