// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace BillingWebJob.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class BillingDetailLineItem
    {
        /// <summary>
        /// Initializes a new instance of the BillingDetailLineItem class.
        /// </summary>
        public BillingDetailLineItem() { }

        /// <summary>
        /// Initializes a new instance of the BillingDetailLineItem class.
        /// </summary>
        public BillingDetailLineItem(string accountOwnerId = default(string), string accountName = default(string), string serviceAdministratorId = default(string), string subscriptionId = default(string), string subscriptionGuid = default(string), string subscriptionName = default(string), DateTime? date = default(DateTime?), int? month = default(int?), int? day = default(int?), int? year = default(int?), string product = default(string), string resourceGUID = default(string), string service = default(string), string serviceType = default(string), string serviceRegion = default(string), string serviceResource = default(string), string resourceQtyConsumed = default(string), string serviceSubRegion = default(string), string serviceInfo = default(string), string component = default(string), string serviceInfo1 = default(string), string serviceInfo2 = default(string), string additionalInfo = default(string), string tags = default(string), string storeServiceIdentifier = default(string), string departmentName = default(string), string costCenter = default(string), string downloadUrl = default(string), string resourceRate = default(string), string extendedCost = default(string), string key = default(string), string resourceKey = default(string))
        {
            AccountOwnerId = accountOwnerId;
            AccountName = accountName;
            ServiceAdministratorId = serviceAdministratorId;
            SubscriptionId = subscriptionId;
            SubscriptionGuid = subscriptionGuid;
            SubscriptionName = subscriptionName;
            Date = date;
            Month = month;
            Day = day;
            Year = year;
            Product = product;
            ResourceGUID = resourceGUID;
            Service = service;
            ServiceType = serviceType;
            ServiceRegion = serviceRegion;
            ServiceResource = serviceResource;
            ResourceQtyConsumed = resourceQtyConsumed;
            ServiceSubRegion = serviceSubRegion;
            ServiceInfo = serviceInfo;
            Component = component;
            ServiceInfo1 = serviceInfo1;
            ServiceInfo2 = serviceInfo2;
            AdditionalInfo = additionalInfo;
            Tags = tags;
            StoreServiceIdentifier = storeServiceIdentifier;
            DepartmentName = departmentName;
            CostCenter = costCenter;
            DownloadUrl = downloadUrl;
            ResourceRate = resourceRate;
            ExtendedCost = extendedCost;
            Key = key;
            ResourceKey = resourceKey;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AccountOwnerId")]
        public string AccountOwnerId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AccountName")]
        public string AccountName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ServiceAdministratorId")]
        public string ServiceAdministratorId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SubscriptionId")]
        public string SubscriptionId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SubscriptionGuid")]
        public string SubscriptionGuid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SubscriptionName")]
        public string SubscriptionName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Date")]
        public DateTime? Date { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Month")]
        public int? Month { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Day")]
        public int? Day { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Year")]
        public int? Year { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Product")]
        public string Product { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ResourceGUID")]
        public string ResourceGUID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Service")]
        public string Service { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ServiceType")]
        public string ServiceType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ServiceRegion")]
        public string ServiceRegion { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ServiceResource")]
        public string ServiceResource { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ResourceQtyConsumed")]
        public string ResourceQtyConsumed { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ServiceSubRegion")]
        public string ServiceSubRegion { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ServiceInfo")]
        public string ServiceInfo { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Component")]
        public string Component { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ServiceInfo1")]
        public string ServiceInfo1 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ServiceInfo2")]
        public string ServiceInfo2 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AdditionalInfo")]
        public string AdditionalInfo { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Tags")]
        public string Tags { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "StoreServiceIdentifier")]
        public string StoreServiceIdentifier { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DepartmentName")]
        public string DepartmentName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CostCenter")]
        public string CostCenter { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DownloadUrl")]
        public string DownloadUrl { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ResourceRate")]
        public string ResourceRate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ExtendedCost")]
        public string ExtendedCost { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Key")]
        public string Key { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ResourceKey")]
        public string ResourceKey { get; private set; }

    }
}
