// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace BillingWebJob.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class CspAzureResourceUsageRecord
    {
        /// <summary>
        /// Initializes a new instance of the CspAzureResourceUsageRecord
        /// class.
        /// </summary>
        public CspAzureResourceUsageRecord() { }

        /// <summary>
        /// Initializes a new instance of the CspAzureResourceUsageRecord
        /// class.
        /// </summary>
        public CspAzureResourceUsageRecord(string category = default(string), double? quantityUsed = default(double?), string resourceId = default(string), string resourceName = default(string), string subcategory = default(string), double? totalCost = default(double?), string unit = default(string), string customerName = default(string), string customerId = default(string), string customerBillingProfile = default(string), string customerCommerceId = default(string), string customerDomain = default(string), string customerTenantId = default(string), string customerRelationshipToPartner = default(string), string subscriptionName = default(string), string subscriptionId = default(string), string subscriptionStatus = default(string), string subscriptionContractType = default(string), DateTime? billingStartDate = default(DateTime?), DateTime? billingEndDate = default(DateTime?))
        {
            Category = category;
            QuantityUsed = quantityUsed;
            ResourceId = resourceId;
            ResourceName = resourceName;
            Subcategory = subcategory;
            TotalCost = totalCost;
            Unit = unit;
            CustomerName = customerName;
            CustomerId = customerId;
            CustomerBillingProfile = customerBillingProfile;
            CustomerCommerceId = customerCommerceId;
            CustomerDomain = customerDomain;
            CustomerTenantId = customerTenantId;
            CustomerRelationshipToPartner = customerRelationshipToPartner;
            SubscriptionName = subscriptionName;
            SubscriptionId = subscriptionId;
            SubscriptionStatus = subscriptionStatus;
            SubscriptionContractType = subscriptionContractType;
            BillingStartDate = billingStartDate;
            BillingEndDate = billingEndDate;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Category")]
        public string Category { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "QuantityUsed")]
        public double? QuantityUsed { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ResourceId")]
        public string ResourceId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ResourceName")]
        public string ResourceName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Subcategory")]
        public string Subcategory { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TotalCost")]
        public double? TotalCost { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Unit")]
        public string Unit { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CustomerName")]
        public string CustomerName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CustomerId")]
        public string CustomerId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CustomerBillingProfile")]
        public string CustomerBillingProfile { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CustomerCommerceId")]
        public string CustomerCommerceId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CustomerDomain")]
        public string CustomerDomain { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CustomerTenantId")]
        public string CustomerTenantId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CustomerRelationshipToPartner")]
        public string CustomerRelationshipToPartner { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SubscriptionName")]
        public string SubscriptionName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SubscriptionId")]
        public string SubscriptionId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SubscriptionStatus")]
        public string SubscriptionStatus { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SubscriptionContractType")]
        public string SubscriptionContractType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "BillingStartDate")]
        public DateTime? BillingStartDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "BillingEndDate")]
        public DateTime? BillingEndDate { get; set; }

    }
}
