// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace BillingWebJob.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class CspUsageLineItem
    {
        /// <summary>
        /// Initializes a new instance of the CspUsageLineItem class.
        /// </summary>
        public CspUsageLineItem() { }

        /// <summary>
        /// Initializes a new instance of the CspUsageLineItem class.
        /// </summary>
        public CspUsageLineItem(int? id = default(int?), DateTime? usageDate = default(DateTime?), string customerBillableAccount = default(string), string partnerId = default(string), string partnerName = default(string), string partnerBillableAccountId = default(string), string customerCompanyName = default(string), string mpnId = default(string), string tierMpnId = default(string), string invoiceNumber = default(string), string subscriptionId = default(string), string subscriptionName = default(string), string subscriptionDescription = default(string), string orderId = default(string), string serviceName = default(string), string serviceType = default(string), string resourceGuid = default(string), string resourceName = default(string), string region = default(string), double? consumedQuantity = default(double?), DateTime? chargeStartDate = default(DateTime?), DateTime? chargeEndDate = default(DateTime?), string billingProvider = default(string))
        {
            Id = id;
            UsageDate = usageDate;
            CustomerBillableAccount = customerBillableAccount;
            PartnerId = partnerId;
            PartnerName = partnerName;
            PartnerBillableAccountId = partnerBillableAccountId;
            CustomerCompanyName = customerCompanyName;
            MpnId = mpnId;
            TierMpnId = tierMpnId;
            InvoiceNumber = invoiceNumber;
            SubscriptionId = subscriptionId;
            SubscriptionName = subscriptionName;
            SubscriptionDescription = subscriptionDescription;
            OrderId = orderId;
            ServiceName = serviceName;
            ServiceType = serviceType;
            ResourceGuid = resourceGuid;
            ResourceName = resourceName;
            Region = region;
            ConsumedQuantity = consumedQuantity;
            ChargeStartDate = chargeStartDate;
            ChargeEndDate = chargeEndDate;
            BillingProvider = billingProvider;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "UsageDate")]
        public DateTime? UsageDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CustomerBillableAccount")]
        public string CustomerBillableAccount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PartnerId")]
        public string PartnerId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PartnerName")]
        public string PartnerName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PartnerBillableAccountId")]
        public string PartnerBillableAccountId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CustomerCompanyName")]
        public string CustomerCompanyName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MpnId")]
        public string MpnId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TierMpnId")]
        public string TierMpnId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "invoiceNumber")]
        public string InvoiceNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SubscriptionId")]
        public string SubscriptionId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SubscriptionName")]
        public string SubscriptionName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SubscriptionDescription")]
        public string SubscriptionDescription { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "orderId")]
        public string OrderId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ServiceName")]
        public string ServiceName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ServiceType")]
        public string ServiceType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ResourceGuid")]
        public string ResourceGuid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ResourceName")]
        public string ResourceName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Region")]
        public string Region { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ConsumedQuantity")]
        public double? ConsumedQuantity { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ChargeStartDate")]
        public DateTime? ChargeStartDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ChargeEndDate")]
        public DateTime? ChargeEndDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "BillingProvider")]
        public string BillingProvider { get; set; }

    }
}
