// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace BillingWebJob.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ResourceAttributes
    {
        /// <summary>
        /// Initializes a new instance of the ResourceAttributes class.
        /// </summary>
        public ResourceAttributes() { }

        /// <summary>
        /// Initializes a new instance of the ResourceAttributes class.
        /// </summary>
        public ResourceAttributes(string etag = default(string), string objectType = default(string))
        {
            Etag = etag;
            ObjectType = objectType;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Etag")]
        public string Etag { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ObjectType")]
        public string ObjectType { get; set; }

    }
}
