// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace BillingWebJob.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class UsageBasedLineItem
    {
        /// <summary>
        /// Initializes a new instance of the UsageBasedLineItem class.
        /// </summary>
        public UsageBasedLineItem() { }

        /// <summary>
        /// Initializes a new instance of the UsageBasedLineItem class.
        /// </summary>
        public UsageBasedLineItem(int? detailLineItemId = default(int?), string sku = default(string), double? includedQuantity = default(double?), double? overageQuantity = default(double?), double? listPrice = default(double?), double? consumptionPrice = default(double?), double? consumptionDiscount = default(double?), string currency = default(string), double? pretaxCharges = default(double?), double? taxAmount = default(double?), double? postTaxTotal = default(double?), double? pretaxEffectiveRate = default(double?), double? postTaxEffectiveRate = default(double?), string chargeType = default(string), int? invoiceLineItemType = default(int?), string partnerId = default(string), string partnerName = default(string), string partnerBillableAccountId = default(string), string customerId = default(string), string customerCompanyName = default(string), int? mpnId = default(int?), int? tier2MpnId = default(int?), string invoiceNumber = default(string), string domainName = default(string), string billingCycleType = default(string), string subscriptionId = default(string), string subscriptionName = default(string), string subscriptionDescription = default(string), string orderId = default(string), string serviceName = default(string), string serviceType = default(string), string resourceGuid = default(string), string resourceName = default(string), string region = default(string), double? consumedQuantity = default(double?), DateTime? chargeStartDate = default(DateTime?), DateTime? chargeEndDate = default(DateTime?), int? billingProvider = default(int?), ResourceAttributes attributes = default(ResourceAttributes))
        {
            DetailLineItemId = detailLineItemId;
            Sku = sku;
            IncludedQuantity = includedQuantity;
            OverageQuantity = overageQuantity;
            ListPrice = listPrice;
            ConsumptionPrice = consumptionPrice;
            ConsumptionDiscount = consumptionDiscount;
            Currency = currency;
            PretaxCharges = pretaxCharges;
            TaxAmount = taxAmount;
            PostTaxTotal = postTaxTotal;
            PretaxEffectiveRate = pretaxEffectiveRate;
            PostTaxEffectiveRate = postTaxEffectiveRate;
            ChargeType = chargeType;
            InvoiceLineItemType = invoiceLineItemType;
            PartnerId = partnerId;
            PartnerName = partnerName;
            PartnerBillableAccountId = partnerBillableAccountId;
            CustomerId = customerId;
            CustomerCompanyName = customerCompanyName;
            MpnId = mpnId;
            Tier2MpnId = tier2MpnId;
            InvoiceNumber = invoiceNumber;
            DomainName = domainName;
            BillingCycleType = billingCycleType;
            SubscriptionId = subscriptionId;
            SubscriptionName = subscriptionName;
            SubscriptionDescription = subscriptionDescription;
            OrderId = orderId;
            ServiceName = serviceName;
            ServiceType = serviceType;
            ResourceGuid = resourceGuid;
            ResourceName = resourceName;
            Region = region;
            ConsumedQuantity = consumedQuantity;
            ChargeStartDate = chargeStartDate;
            ChargeEndDate = chargeEndDate;
            BillingProvider = billingProvider;
            Attributes = attributes;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DetailLineItemId")]
        public int? DetailLineItemId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Sku")]
        public string Sku { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IncludedQuantity")]
        public double? IncludedQuantity { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "OverageQuantity")]
        public double? OverageQuantity { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ListPrice")]
        public double? ListPrice { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ConsumptionPrice")]
        public double? ConsumptionPrice { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ConsumptionDiscount")]
        public double? ConsumptionDiscount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Currency")]
        public string Currency { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PretaxCharges")]
        public double? PretaxCharges { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TaxAmount")]
        public double? TaxAmount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PostTaxTotal")]
        public double? PostTaxTotal { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PretaxEffectiveRate")]
        public double? PretaxEffectiveRate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PostTaxEffectiveRate")]
        public double? PostTaxEffectiveRate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ChargeType")]
        public string ChargeType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "InvoiceLineItemType")]
        public int? InvoiceLineItemType { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PartnerId")]
        public string PartnerId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PartnerName")]
        public string PartnerName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PartnerBillableAccountId")]
        public string PartnerBillableAccountId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CustomerId")]
        public string CustomerId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CustomerCompanyName")]
        public string CustomerCompanyName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MpnId")]
        public int? MpnId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Tier2MpnId")]
        public int? Tier2MpnId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "InvoiceNumber")]
        public string InvoiceNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DomainName")]
        public string DomainName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "BillingCycleType")]
        public string BillingCycleType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SubscriptionId")]
        public string SubscriptionId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SubscriptionName")]
        public string SubscriptionName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SubscriptionDescription")]
        public string SubscriptionDescription { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "OrderId")]
        public string OrderId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ServiceName")]
        public string ServiceName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ServiceType")]
        public string ServiceType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ResourceGuid")]
        public string ResourceGuid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ResourceName")]
        public string ResourceName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Region")]
        public string Region { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ConsumedQuantity")]
        public double? ConsumedQuantity { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ChargeStartDate")]
        public DateTime? ChargeStartDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ChargeEndDate")]
        public DateTime? ChargeEndDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "BillingProvider")]
        public int? BillingProvider { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Attributes")]
        public ResourceAttributes Attributes { get; private set; }

    }
}
