// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace BillingWebJob.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class UsageInfoModel
    {
        /// <summary>
        /// Initializes a new instance of the UsageInfoModel class.
        /// </summary>
        public UsageInfoModel() { }

        /// <summary>
        /// Initializes a new instance of the UsageInfoModel class.
        /// </summary>
        public UsageInfoModel(int? usageInfoModelId = default(int?), string subceriptionId = default(string), string organizationId = default(string), string meterName = default(string), string meterCategory = default(string), string meteredRegion = default(string), string meterSubCategory = default(string), string usageStartTime = default(string), string usageEndTime = default(string), string meteredService = default(string), string meteredServiceType = default(string), string userProject = default(string), double? quantity = default(double?), double? itemTotal = default(double?))
        {
            UsageInfoModelId = usageInfoModelId;
            SubceriptionId = subceriptionId;
            OrganizationId = organizationId;
            MeterName = meterName;
            MeterCategory = meterCategory;
            MeteredRegion = meteredRegion;
            MeterSubCategory = meterSubCategory;
            UsageStartTime = usageStartTime;
            UsageEndTime = usageEndTime;
            MeteredService = meteredService;
            MeteredServiceType = meteredServiceType;
            UserProject = userProject;
            Quantity = quantity;
            ItemTotal = itemTotal;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "UsageInfoModelId")]
        public int? UsageInfoModelId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SubceriptionId")]
        public string SubceriptionId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "OrganizationId")]
        public string OrganizationId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MeterName")]
        public string MeterName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MeterCategory")]
        public string MeterCategory { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MeteredRegion")]
        public string MeteredRegion { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MeterSubCategory")]
        public string MeterSubCategory { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "UsageStartTime")]
        public string UsageStartTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "UsageEndTime")]
        public string UsageEndTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MeteredService")]
        public string MeteredService { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MeteredServiceType")]
        public string MeteredServiceType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "UserProject")]
        public string UserProject { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Quantity")]
        public double? Quantity { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ItemTotal")]
        public double? ItemTotal { get; set; }

    }
}
